environment: prod

catalyst:
  region: in

aws:
  region: ap-south-1
  instance_size: medium

azure:
  region: centralindia
  sku: S1

gcp:
  region: asia-south1
  machine_type: e2-medium

alibaba:
  region: ap-south-1
  instance_type: ecs.c6.large

compute:
  replicas: 2
